updated couch potato init script

diff --git a/couchpotato b/couchpotato
--- a/couchpotato
+++ b/couchpotato
@@ -1,57 +1,67 @@
 #! /bin/sh
 
 ### BEGIN INIT INFO
-# Provides:          CouchPotato application instance
-# Required-Start:    $all
-# Required-Stop:     $all
+# Provides:          couchpotato
+# Required-Start:    $local_fs $network $remote_fs
+# Required-Stop:     $local_fs $network $remote_fs
+# Should-Start:      $NetworkManager
+# Should-Stop:       $NetworkManager
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: starts instance of CouchPotato
 # Description:       starts instance of CouchPotato using start-stop-daemon
 ### END INIT INFO
 
-############### EDIT ME ##################
-# path to app
-APP_PATH=/home/ffej/.couchpotato
+# Check for existance of defaults file
+# and utilze if available
+if [ -f /etc/default/couchpotato ]; then
+    . /etc/default/couchpotato
+else
+    echo "/etc/default/couchpotato not found using default settings.";
+fi
 
-# path to python bin
-DAEMON=/usr/bin/python
-
-# startup args
-DAEMON_OPTS=" CouchPotato.py -q"
-
-# script name
+# Script name
 NAME=couchpotato
 
-# app name
+# App name
 DESC=CouchPotato
 
-# user
-RUN_AS=ffej
+# Path to app root
+CP_APP_PATH=/home/ffej/.couchpotato
 
-PID_FILE=/var/run/couchpotato.pid
+# User to run CP as
+CP_RUN_AS=ffej
 
-############### END EDIT ME ##################
+# Path to python bin
+CP_DAEMON=/usr/bin/python
 
-test -x $DAEMON || exit 0
+# Path to store PID file
+CP_PID_FILE=/var/run/couchpotato.pid
+
+# Other startup args
+CP_DAEMON_OPTS=" CouchPotato.py --daemon --pid_file=${CP_PID_FILE}"
+
+test -x $CP_DAEMON || exit 0
 
 set -e
 
 case "$1" in
   start)
         echo "Starting $DESC"
-        start-stop-daemon -d $APP_PATH -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
+        rm -rf $CP_PID_FILE || return 1
+        touch $CP_PID_FILE
+        chown $CP_RUN_AS $CP_PID_FILE
+        start-stop-daemon -d $CP_APP_PATH -c $CP_RUN_AS --start --background --pidfile $CP_PID_FILE --exec $CP_DAEMON -- $CP_DAEMON_OPTS
         ;;
   stop)
         echo "Stopping $DESC"
-        start-stop-daemon --stop --pidfile $PID_FILE
+        start-stop-daemon --stop --pidfile $CP_PID_FILE --retry 15
         ;;
 
   restart|force-reload)
         echo "Restarting $DESC"
-        start-stop-daemon --stop --pidfile $PID_FILE
-        sleep 15
-        start-stop-daemon -d $APP_PATH -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
+        start-stop-daemon --stop --pidfile $CP_PID_FILE --retry 15
+        start-stop-daemon -d $CP_APP_PATH -c $CP_RUN_AS --start --background --pidfile $CP_PID_FILE --exec $CP_DAEMON -- $CP_DAEMON_OPTS
         ;;
   *)
         N=/etc/init.d/$NAME
